apiVersion: v1
kind: Service
metadata:
  name: llmtrain-headless
  labels:
    app: llmtrain
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: llmtrain
  ports:
    - name: dist
      port: 29500
      targetPort: 29500
